name: ML Training CI

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Run actions/checkout@v3
        uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      - name: Check Env
        run: python --version

      - name: Install dependencies
        run: |
          pip install mlflow==2.19.0 scikit-learn pandas numpy imbalanced-learn dagshub

      - name: Run mlflow project
        env:
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
          MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
        run: |
          cd MLProject
          mlflow run . --env-manager=local 2>&1 | tee /tmp/mlflow_output.txt
          RUN_ID=$(grep "Run (ID" /tmp/mlflow_output.txt | grep -o "'[a-z0-9]*'" | tr -d "'")
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT
          echo "Captured RUN_ID: $RUN_ID"

      - name: Get latest MLflow run_id
        run: echo "Run ID is ${{ env.RUN_ID }}"

      - name: Install Python dependencies
        run: pip install mlflow==2.19.0

      - name: Upload to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: MLProject/

      - name: Build Docker Model
        env:
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
          MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
        run: |
          mlflow models build-docker \
            -m "runs:/${{ env.RUN_ID }}/model" \
            -n "fayaesph/diabetes-prediction" \
            --enable-mlserver

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag Docker Image
        run: docker tag fayaesph/diabetes-prediction fayaesph/diabetes-prediction:latest

      - name: Push Docker Image
        run: docker push fayaesph/diabetes-prediction:latest